GRANT USAGE ON *.* TO 'mod'@'localhost' IDENTIFIED BY PASSWORD '*234DBDC179926A158DCCC531D05E52D34EA85B8E';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `net\_articles`.* TO 'mod'@'localhost';


